In [1]:

from pathlib import Path
import pandas as pd

print("Current notebook folder:", Path.cwd())

for filename in [
    "Coffee_export.csv",
    "Coffee_import.csv",
    "Coffee_production.csv"
]:
    print(filename, "exists:", Path(filename).exists())

Current notebook folder: /Users/williamanderson/Ds-envirornment/coffee-exploration
Coffee_export.csv exists: True
Coffee_import.csv exists: True
Coffee_production.csv exists: True

In [2]:
# Part 1: Load the Coffee Data
# Import pandas to work with CSV files and DataFrames.

import pandas as pd
# Load each CSV file into its own DataFrame.
# Each DataFrame stores the data for one coffee trade category.

coffee_export = pd.read_csv("Coffee_export.csv")
coffee_import = pd.read_csv("Coffee_import.csv")
coffee_production = pd.read_csv("Coffee_production.csv")


print("All three datasets loaded successfully.")

All three datasets loaded successfully.

In [3]:
# Display the first five rows of each DataFrame to preview the data.

print("COFFEE EXPORTS")
display(coffee_export.head())

print("COFFEE IMPORTS")
display(coffee_import.head())

print("COFFEE PRODUCTION")
display(coffee_production.head())

COFFEE EXPORTS

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
0,Angola,5040000,4260000,4800000,2340000,480000,2460000,3120000,3000000,3240000,...,480000,480000,360000,540000,660000,660000,540000,540000,1380000,43320000
1,Bolivia (Plurinational State of),9360000,4440000,5760000,2820000,5040000,5640000,7380000,6660000,5820000,...,4440000,3780000,3300000,3720000,1800000,1320000,1560000,1320000,1200000,137460000
2,Brazil,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,...,2028360000,1712940000,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056
3,Burundi,35100000,41280000,38760000,25080000,30480000,31680000,13440000,31740000,22440000,...,13080000,23520000,11700000,15120000,13800000,12240000,10140000,12120000,17580000,646200000
4,Cameroon,156660000,105120000,98760000,42300000,32760000,24420000,33840000,82080000,44760000,...,29400000,37320000,16320000,22500000,23400000,16860000,14700000,17220000,15000000,1399920000

COFFEE IMPORTS

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
0,Austria,112800000,123480000,132360000,110160000,85020000,73860000,72600000,77640000,77580000,...,87120000,93540000,93300000,91500000,90780000,89700000,87600000,85740000,86880000,2765760000
1,Belgium,0,0,0,0,0,0,0,0,0,...,349680000,340080000,330120000,312720000,332040000,363120000,340620000,344520000,371940000,6240540000
2,Belgium/Luxembourg,120900000,104760000,109680000,123780000,135720000,144060000,151560000,152640000,214800000,...,0,0,0,0,0,0,0,0,0,1257900000
3,Bulgaria,16080000,12000000,10920000,23820000,27780000,30900000,16320000,17640000,20520000,...,28920000,33600000,36540000,37260000,40920000,46740000,42420000,44220000,47100000,830700000
4,Croatia,0,0,10080000,9780000,11580000,19200000,19320000,23100000,20340000,...,23460000,23040000,24780000,25200000,26220000,28740000,26340000,26760000,27960000,622080000

COFFEE PRODUCTION

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
0,Angola,Robusta/Arabica,3.000000e+06,4.740000e+06,4.680000e+06,1.980000e+06,4.620000e+06,3.720000e+06,4.260000e+06,3.840000e+06,...,1.740000e+06,1.980000e+06,2.100000e+06,2.340000e+06,2.460000e+06,2.700000e+06,2.100000e+06,2.520000e+06,3.120000e+06,8.208000e+07
1,Bolivia (Plurinational State of),Arabica,7.380000e+06,6.240000e+06,7.200000e+06,3.060000e+06,7.020000e+06,8.520000e+06,7.500000e+06,8.460000e+06,...,7.920000e+06,6.300000e+06,7.200000e+06,6.000000e+06,5.040000e+06,4.680000e+06,5.040000e+06,4.980000e+06,4.860000e+06,2.070000e+08
2,Brazil,Arabica/Robusta,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10
3,Burundi,Arabica/Robusta,2.922000e+07,4.002000e+07,3.720000e+07,2.358000e+07,3.984000e+07,2.604000e+07,2.406000e+07,1.500000e+07,...,1.224000e+07,2.436000e+07,9.780000e+06,1.488000e+07,1.614000e+07,1.176000e+07,1.212000e+07,1.224000e+07,1.632000e+07,6.236400e+08
4,Ecuador,Arabica/Robusta,9.024000e+07,1.274400e+08,7.110000e+07,1.241400e+08,1.425600e+08,1.132800e+08,1.195800e+08,7.146000e+07,...,4.950000e+07,4.968000e+07,3.996000e+07,3.864000e+07,3.864000e+07,3.870000e+07,3.744000e+07,2.976000e+07,3.354000e+07,1.900380e+09

In [4]:
# Part 2: Explore the Datasets
# Examine the size, columns, data types, missing values,
# duplicate rows, year ranges, and countries in each dataset.

datasets = {
    "Coffee Exports": coffee_export,
    "Coffee Imports": coffee_import,
    "Coffee Production": coffee_production
}

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(name)
    print("=" * 50)
    
    # Show the number of rows and columns.
    print("Rows and columns:", df.shape)
    
    # List all column names.
    print("\nColumn names:")
    print(df.columns.tolist())
    
     # Display each column's data type.
    print("\nData types and non-missing counts:")
    df.info()

==================================================
Coffee Exports
==================================================
Rows and columns: (55, 32)

Column names:
['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_export']

Data types and non-missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       55 non-null     str
 1   1990          55 non-null     int64
 2   1991          55 non-null     int64
 3   1992          55 non-null     int64
 4   1993          55 non-null     int64
 5   1994          55 non-null     int64
 6   1995          55 non-null     int64
 7   1996          55 non-null     int64
 8   1997          55 non-null     int64
 9   1998          55 non-null     int64
 10  1999          55 non-null     int64
 11  2000          55 non-null     int64
 12  2001          55 non-null     int64
 13  2002          55 non-null     int64
 14  2003          55 non-null     int64
 15  2004          55 non-null     int64
 16  2005          55 non-null     int64
 17  2006          55 non-null     int64
 18  2007          55 non-null     int64
 19  2008          55 non-null     int64
 20  2009          55 non-null     int64
 21  2010          55 non-null     int64
 22  2011          55 non-null     int64
 23  2012          55 non-null     int64
 24  2013          55 non-null     int64
 25  2014          55 non-null     int64
 26  2015          55 non-null     int64
 27  2016          55 non-null     int64
 28  2017          55 non-null     int64
 29  2018          55 non-null     int64
 30  2019          55 non-null     int64
 31  Total_export  55 non-null     int64
dtypes: int64(31), str(1)
memory usage: 13.9 KB

==================================================
Coffee Imports
==================================================
Rows and columns: (35, 32)

Column names:
['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_import']

Data types and non-missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       35 non-null     str
 1   1990          35 non-null     int64
 2   1991          35 non-null     int64
 3   1992          35 non-null     int64
 4   1993          35 non-null     int64
 5   1994          35 non-null     int64
 6   1995          35 non-null     int64
 7   1996          35 non-null     int64
 8   1997          35 non-null     int64
 9   1998          35 non-null     int64
 10  1999          35 non-null     int64
 11  2000          35 non-null     int64
 12  2001          35 non-null     int64
 13  2002          35 non-null     int64
 14  2003          35 non-null     int64
 15  2004          35 non-null     int64
 16  2005          35 non-null     int64
 17  2006          35 non-null     int64
 18  2007          35 non-null     int64
 19  2008          35 non-null     int64
 20  2009          35 non-null     int64
 21  2010          35 non-null     int64
 22  2011          35 non-null     int64
 23  2012          35 non-null     int64
 24  2013          35 non-null     int64
 25  2014          35 non-null     int64
 26  2015          35 non-null     int64
 27  2016          35 non-null     int64
 28  2017          35 non-null     int64
 29  2018          35 non-null     int64
 30  2019          35 non-null     int64
 31  Total_import  35 non-null     int64
dtypes: int64(31), str(1)
memory usage: 8.9 KB

==================================================
Coffee Production
==================================================
Rows and columns: (55, 33)

Column names:
['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94', '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00', '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', 'Total_production']

Data types and non-missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           55 non-null     str
 1   Coffee type       55 non-null     str
 2   1990/91           55 non-null     float64
 3   1991/92           55 non-null     float64
 4   1992/93           55 non-null     float64
 5   1993/94           55 non-null     float64
 6   1994/95           55 non-null     float64
 7   1995/96           55 non-null     float64
 8   1996/97           55 non-null     float64
 9   1997/98           55 non-null     float64
 10  1998/99           55 non-null     float64
 11  1999/00           55 non-null     float64
 12  2000/01           55 non-null     float64
 13  2001/02           55 non-null     float64
 14  2002/03           55 non-null     float64
 15  2003/04           55 non-null     float64
 16  2004/05           55 non-null     float64
 17  2005/06           55 non-null     float64
 18  2006/07           55 non-null     float64
 19  2007/08           55 non-null     float64
 20  2008/09           55 non-null     float64
 21  2009/10           55 non-null     float64
 22  2010/11           55 non-null     float64
 23  2011/12           55 non-null     float64
 24  2012/13           55 non-null     float64
 25  2013/14           55 non-null     float64
 26  2014/15           55 non-null     float64
 27  2015/16           55 non-null     float64
 28  2016/17           55 non-null     float64
 29  2017/18           55 non-null     float64
 30  2018/19           55 non-null     float64
 31  2019/20           55 non-null     float64
 32  Total_production  55 non-null     float64
dtypes: float64(31), str(2)
memory usage: 14.3 KB

In [5]:

# Part 2: Explore the Datasets
# Create a dictionary that connects each dataset name to its DataFrame.
datasets = {
    "Coffee Exports": coffee_export,
    "Coffee Imports": coffee_import,
    "Coffee Production": coffee_production
}
# Add rows and columns
# Loop through each dataset so we can inspect them using the same steps.
for name, df in datasets.items():

    # Print the dataset name as a heading.
    print(f"\n--- {name} ---")

    # Display the number of rows (records) in the dataset.
    print(f"Rows: {df.shape[0]}")

    # Display the number of columns (variables) in the dataset.
    print(f"Columns: {df.shape[1]}")

    # Count all missing cells across every row and column.
    print(f"Missing cells: {df.isna().sum().sum()}")

    # Count rows that are exact duplicates of earlier rows.
    print(f"Duplicate rows: {df.duplicated().sum()}")

    # Display each column's data type, such as text or numbers.
    print("Data types:")
    print(df.dtypes)

--- Coffee Exports ---
Rows: 55
Columns: 32
Missing cells: 0
Duplicate rows: 0
Data types:
Country           str
1990            int64
1991            int64
1992            int64
1993            int64
1994            int64
1995            int64
1996            int64
1997            int64
1998            int64
1999            int64
2000            int64
2001            int64
2002            int64
2003            int64
2004            int64
2005            int64
2006            int64
2007            int64
2008            int64
2009            int64
2010            int64
2011            int64
2012            int64
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_export    int64
dtype: object

--- Coffee Imports ---
Rows: 35
Columns: 32
Missing cells: 0
Duplicate rows: 0
Data types:
Country           str
1990            int64
1991            int64
1992            int64
1993            int64
1994            int64
1995            int64
1996            int64
1997            int64
1998            int64
1999            int64
2000            int64
2001            int64
2002            int64
2003            int64
2004            int64
2005            int64
2006            int64
2007            int64
2008            int64
2009            int64
2010            int64
2011            int64
2012            int64
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_import    int64
dtype: object

--- Coffee Production ---
Rows: 55
Columns: 33
Missing cells: 0
Duplicate rows: 0
Data types:
Country                 str
Coffee type             str
1990/91             float64
1991/92             float64
1992/93             float64
1993/94             float64
1994/95             float64
1995/96             float64
1996/97             float64
1997/98             float64
1998/99             float64
1999/00             float64
2000/01             float64
2001/02             float64
2002/03             float64
2003/04             float64
2004/05             float64
2005/06             float64
2006/07             float64
2007/08             float64
2008/09             float64
2009/10             float64
2010/11             float64
2011/12             float64
2012/13             float64
2013/14             float64
2014/15             float64
2015/16             float64
2016/17             float64
2017/18             float64
2018/19             float64
2019/20             float64
Total_production    float64
dtype: object

In [6]:
# print Brazils coffee export: years in rows and columns.
print("Brazil's coffee export values:")
display(
    coffee_export.loc[
        coffee_export["Country"] == "Brazil",
        ["Country", "2013", "2014", "2015", "2016", "2019", "Total_export"]
    ]
)

Brazil's coffee export values:

,Country,2013,2014,2015,2016,2019,Total_export
2,Brazil,1899060000,-2147483648,-2147483648,2056140000,-2147483648,33807709056

In [7]:
#print each coffee title and the total row and columns for each title.
print("COFFEE EXPORTS")
print(coffee_export.shape)
print(coffee_export.columns.tolist())

print("\nCOFFEE IMPORTS")
print(coffee_import.shape)
print(coffee_import.columns.tolist())

print("\nCOFFEE PRODUCTION")
print(coffee_production.shape)
print(coffee_production.columns.tolist())

COFFEE EXPORTS
(55, 32)
['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_export']

COFFEE IMPORTS
(35, 32)
['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_import']

COFFEE PRODUCTION
(55, 33)
['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94', '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00', '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', 'Total_production']

In [8]:

for name, df in {
    "Coffee Exports": coffee_export,
    "Coffee Imports": coffee_import,
    "Coffee Production": coffee_production
}.items():
    print(f"\n{'=' * 50}")
    print(name)
    print("=" * 50)

    numeric_df = df.select_dtypes(include="number")
    display(numeric_df.describe().round(2))

# Calculate the minimum, maximum, and average of each dataset's
# total metric to compare the overall values across countries.
total_columns = {
    "Coffee Exports": (coffee_export, "Total_export"),
    "Coffee Imports": (coffee_import, "Total_import"),
    "Coffee Production": (coffee_production, "Total_production")
}

for name, (df, total_column) in total_columns.items():
    print(f"\n{name} — {total_column}")

==================================================
Coffee Exports
==================================================

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,...,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01
mean,8.800800e+07,8.284691e+07,8.541382e+07,8.200036e+07,7.713600e+07,7.404436e+07,8.472982e+07,8.775055e+07,8.753673e+07,9.397091e+07,...,1.114767e+08,1.183015e+08,1.184389e+08,4.627702e+07,4.695557e+07,1.323622e+08,1.303887e+08,1.381047e+08,6.021884e+07,2.851332e+09
std,1.832890e+08,2.019180e+08,2.031566e+08,1.852049e+08,1.719033e+08,1.471032e+08,1.634044e+08,1.761129e+08,1.836647e+08,2.146255e+08,...,3.121420e+08,3.032438e+08,3.130926e+08,3.818677e+08,3.713066e+08,3.763857e+08,3.407518e+08,3.927493e+08,3.977899e+08,6.261177e+09
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,-2.147484e+09,-2.147484e+09,0.000000e+00,0.000000e+00,0.000000e+00,-2.147484e+09,1.500000e+06
25%,4.020000e+06,3.960000e+06,2.310000e+06,2.220000e+06,1.860000e+06,2.370000e+06,1.680000e+06,2.220000e+06,1.800000e+06,2.220000e+06,...,5.400000e+05,4.500000e+05,3.600000e+05,5.700000e+05,4.500000e+05,6.600000e+05,5.700000e+05,5.100000e+05,3.900000e+05,6.084000e+07
50%,1.578000e+07,9.300000e+06,9.960000e+06,1.308000e+07,9.180000e+06,1.200000e+07,9.360000e+06,1.218000e+07,1.284000e+07,1.806000e+07,...,7.920000e+06,8.220000e+06,4.200000e+06,3.720000e+06,3.540000e+06,4.560000e+06,3.480000e+06,6.660000e+06,3.180000e+06,3.160800e+08
75%,1.055700e+08,8.502000e+07,7.971000e+07,7.818000e+07,8.499000e+07,8.970000e+07,1.055100e+08,9.048000e+07,9.099000e+07,9.414000e+07,...,8.133000e+07,8.862000e+07,7.818000e+07,5.808000e+07,4.743000e+07,6.420000e+07,4.947000e+07,6.234000e+07,5.625000e+07,2.552670e+09
max,1.016160e+09,1.270980e+09,1.127460e+09,1.070280e+09,1.036380e+09,8.680800e+08,9.150600e+08,1.008060e+09,1.088640e+09,1.388940e+09,...,2.028360e+09,1.712940e+09,1.899060e+09,1.565820e+09,1.316640e+09,2.056140e+09,1.855500e+09,2.138220e+09,1.644000e+09,3.380771e+10

==================================================
Coffee Imports
==================================================

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
count,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,...,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01
mean,1.270834e+08,1.221943e+08,1.357989e+08,1.322023e+08,1.286126e+08,1.240646e+08,1.334674e+08,1.389651e+08,1.418863e+08,1.464549e+08,...,1.916794e+08,1.940109e+08,1.987337e+08,2.057606e+08,2.080800e+08,2.187960e+08,2.161097e+08,2.227629e+08,2.313326e+08,5.069693e+09
std,2.543488e+08,2.435393e+08,2.690354e+08,2.424808e+08,2.178530e+08,2.188911e+08,2.415144e+08,2.500391e+08,2.548447e+08,2.715283e+08,...,3.363666e+08,3.404099e+08,3.453368e+08,3.539295e+08,3.511787e+08,3.667628e+08,3.684394e+08,3.678250e+08,3.854538e+08,8.850559e+09
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.970000e+07
25%,6.300000e+05,4.800000e+05,6.180000e+06,7.890000e+06,8.880000e+06,8.550000e+06,9.750000e+06,1.074000e+07,1.077000e+07,1.176000e+07,...,2.151000e+07,2.163000e+07,2.373000e+07,2.499000e+07,2.595000e+07,2.835000e+07,2.613000e+07,2.937000e+07,2.946000e+07,5.573100e+08
50%,3.444000e+07,3.150000e+07,3.618000e+07,4.008000e+07,4.626000e+07,3.798000e+07,4.458000e+07,4.362000e+07,4.572000e+07,4.740000e+07,...,5.712000e+07,6.456000e+07,6.378000e+07,6.360000e+07,6.264000e+07,6.804000e+07,6.564000e+07,6.960000e+07,7.320000e+07,1.640040e+09
75%,1.168500e+08,1.141200e+08,1.210200e+08,1.169700e+08,1.246500e+08,1.251600e+08,1.335000e+08,1.439100e+08,1.546500e+08,1.491000e+08,...,2.276100e+08,2.300700e+08,2.283900e+08,2.500500e+08,2.665800e+08,2.949900e+08,3.017100e+08,3.242400e+08,3.272400e+08,5.841240e+09
max,1.260420e+09,1.190400e+09,1.376340e+09,1.159740e+09,9.702600e+08,1.026420e+09,1.166700e+09,1.220580e+09,1.261800e+09,1.364760e+09,...,1.565580e+09,1.563360e+09,1.620960e+09,1.653900e+09,1.662480e+09,1.730280e+09,1.769280e+09,1.735080e+09,1.851240e+09,4.250766e+10

==================================================
Coffee Production
==================================================

,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,1999/00,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,...,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01
mean,1.017055e+08,1.104753e+08,1.074775e+08,1.001007e+08,1.017971e+08,9.525927e+07,1.127029e+08,1.089676e+08,1.187629e+08,1.433280e+08,...,1.541749e+08,1.649280e+08,1.679007e+08,1.639625e+08,1.703193e+08,1.770742e+08,1.785742e+08,1.881415e+08,1.800578e+08,4.104269e+09
std,2.510875e+08,2.668466e+08,3.022180e+08,2.489344e+08,2.510328e+08,1.858680e+08,2.602192e+08,2.430145e+08,3.142337e+08,4.012591e+08,...,4.469919e+08,4.931417e+08,5.030529e+08,4.918727e+08,5.059698e+08,5.225472e+08,5.135587e+08,5.851111e+08,5.390922e+08,1.112550e+10
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.080000e+06
25%,2.430000e+06,3.900000e+06,2.640000e+06,2.130000e+06,2.610000e+06,2.610000e+06,2.340000e+06,2.880000e+06,3.480000e+06,3.540000e+06,...,1.980000e+06,1.710000e+06,2.010000e+06,2.250000e+06,2.310000e+06,1.890000e+06,2.160000e+06,2.190000e+06,2.280000e+06,8.199000e+07
50%,2.766000e+07,2.778000e+07,3.000000e+07,2.652000e+07,2.436000e+07,2.604000e+07,2.406000e+07,1.800000e+07,2.634000e+07,2.184000e+07,...,2.094000e+07,2.004000e+07,1.548000e+07,1.488000e+07,1.758000e+07,1.620000e+07,1.584000e+07,1.860000e+07,1.842000e+07,6.236400e+08
75%,9.216000e+07,9.720000e+07,9.234000e+07,9.486000e+07,1.153200e+08,1.127700e+08,1.139700e+08,9.669000e+07,1.076700e+08,1.211700e+08,...,9.735000e+07,9.189000e+07,7.185000e+07,6.960000e+07,6.657000e+07,6.864000e+07,7.053000e+07,7.806000e+07,7.194000e+07,2.785140e+09
max,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,2.205660e+09,2.854680e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10

Coffee Exports — Total_export

Coffee Imports — Total_import

Coffee Production — Total_production

## Part 3: Descriptive Statistics and Key Findings

I used Pandas' `describe()` method to examine the numerical columns and calculated the minimum, maximum, and mean for each dataset's total metric.

### Summary of Total Values

| Dataset | Minimum | Maximum | Average (Mean) |
|---|---:|---:|---:|
| Coffee Exports | 1,500,000 | 33,807,710,000 | 2,851,332,000 |
| Coffee Imports | 29,700,000 | 42,507,660,000 | 5,069,693,000 |
| Coffee Production | 1,080,000 | 75,082,980,000 | 4,104,269,000 |

*Note: Values are rounded for readability. The dataset's units should be verified before interpreting these numbers as a specific physical quantity.*

### Observations

**Coffee exports:** The maximum total export value is approximately 33.81 billion, and the average is approximately 2.85 billion. I also found three suspicious values of -2,147,483,648 in Brazil's export data for 2014, 2015, and 2019. These negative values may affect year-level statistics and trend comparisons, so they require further investigation.

**Coffee imports:** The maximum total import value is approximately 42.51 billion, and the average is approximately 5.07 billion. The minimum is 29.7 million. These figures show that the total import values vary considerably among the countries in the dataset.

**Coffee production:** The maximum total production value is approximately 75.08 billion, and the average is approximately 4.10 billion. Brazil has the highest total production value in this dataset. The production data uses coffee seasons, such as 2018/19 and 2019/20, rather than calendar years.

**Overall:** The maximum is higher than the average in all three datasets, suggesting that a relatively small number of countries may have much larger totals than others. This should be investigated further by examining the distributions and comparing individual countries. These summary statistics describe the data but do not, by themselves, establish the causes of differences among countries.

In [9]:

print("TOP 10 COFFEE EXPORTERS")
display(
    coffee_export[["Country", "Total_export"]]
    .sort_values("Total_export", ascending=False)
    .head(10)
)

print("TOP 10 COFFEE IMPORTERS")
display(
    coffee_import[["Country", "Total_import"]]
    .sort_values("Total_import", ascending=False)
    .head(10)
)

print("TOP 10 COFFEE PRODUCERS")
display(
    coffee_production[["Country", "Total_production"]]
    .sort_values("Total_production", ascending=False)
    .head(10)
)

TOP 10 COFFEE EXPORTERS

      Country  Total_export
2      Brazil   33807709056
51   Viet Nam   24924480000
6    Colombia   19878480000
25  Indonesia   10607940000
24      India    6933960000
19  Guatemala    6464340000
23   Honduras    5964840000
49     Uganda    5632200000
32     Mexico    5628000000
39       Peru    4903920000

TOP 10 COFFEE IMPORTERS

                     Country  Total_import
34  United States of America   42507660000
11                   Germany   31481400000
15                     Italy   13272120000
28                     Japan   12422760000
10                    France   11972520000
26                     Spain    7840620000
33            United Kingdom    6731460000
1                    Belgium    6240540000
20               Netherlands    5951400000
30        Russian Federation    5731080000

TOP 10 COFFEE PRODUCERS

      Country  Total_production
2      Brazil      7.508298e+10
53   Viet Nam      2.880318e+10
23   Colombia      2.159862e+10
5   Indonesia      1.540488e+10
29   Ethiopia      8.669520e+09
36      India      8.222220e+09
41     Mexico      7.853520e+09
32  Guatemala      7.020540e+09
35   Honduras      6.672720e+09
51     Uganda      5.919480e+09

### Coffee Production Data Quality

The coffee production dataset contains 55 rows and 33 columns, representing 55 countries. My checks found no missing cells or duplicate rows. The dataset includes a `Country` column, a `Coffee type` column, 30 coffee-season year columns from `1990/91` through `2019/20`, and a `Total_production` column.

One consideration is that production data uses coffee-season years, whereas the export and import datasets use calendar years. This difference should be considered before comparing annual trends across the datasets. Although the production dataset passed the missing-value and duplicate checks, these checks alone do not guarantee that every value is accurate.

In [10]:
exporters = set(
    coffee_export.nlargest(10, "Total_export")["Country"]
)

importers = set(
    coffee_import.nlargest(10, "Total_import")["Country"]
)

producers = set(
    coffee_production.nlargest(10, "Total_production")["Country"]
)

print("In the top 10 for all three datasets:")
print(sorted(exporters & importers & producers))

print("\nIn the top 10 for exports and production:")
print(sorted(exporters & producers))

print("\nIn the top 10 for imports and production:")
print(sorted(importers & producers))

In the top 10 for all three datasets:
[]

In the top 10 for exports and production:
['Brazil', 'Colombia', 'Guatemala', 'Honduras', 'India', 'Indonesia', 'Mexico', 'Uganda', 'Viet Nam']

In the top 10 for imports and production:
[]

In [11]:
# Inspect Brazil's export values around the suspicious years

brazil_exports = coffee_export.loc[
    coffee_export["Country"] == "Brazil"
]

display(
    brazil_exports[
        ["Country", "2013", "2014", "2015", "2016", "2017",
         "2018", "2019", "Total_export"]
    ]
)

,Country,2013,2014,2015,2016,2017,2018,2019,Total_export
2,Brazil,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056

In [12]:
print("Data types of Brazil's export columns:")
print(
    brazil_exports[
        ["2013", "2014", "2015", "2016", "2017",
         "2018", "2019", "Total_export"]
    ].dtypes
)

Data types of Brazil's export columns:
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_export    int64
dtype: object

In [13]:
# Count occurrences of the suspicious value in each export column

suspicious_value = -2147483648

print("Count of suspicious values by column:")
print((coffee_export == suspicious_value).sum())

print("\nRows containing the suspicious value:")
display(
    coffee_export[
        (coffee_export == suspicious_value).any(axis=1)
    ]
)

Count of suspicious values by column:
Country         0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            1
2015            1
2016            0
2017            0
2018            0
2019            1
Total_export    0
dtype: int64

Rows containing the suspicious value:

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
2,Brazil,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,...,2028360000,1712940000,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056



Coffee Exports

The coffee exports dataset contains 55 rows and 32 columns. My checks found zero missing cells and zero duplicate rows. However, I identified three suspicious negative values of -2147483648 in Brazil's export data for 2014, 2015, and 2019. These values are unusual for export data and may indicate a data-quality or data-conversion issue. The exact cause has been confirmed and found: The values exist: Brazil's export data contains -2147483648 for 2014, 2015, and 2019.

The original CSV contains them: You loaded Coffee_export.csv as text and confirmed that the negative values were already in the file, rather than being introduced simply by loading it into Pandas.

The total matches the sum: Brazil's Total_export matches the sum of its yearly values, but that sum includes the three suspicious negative numbers. Therefore, the matching total does not prove the data is accurate.

In [14]:
# Read the original CSV without changing the existing dataframe
raw_exports = pd.read_csv(
    "Coffee_export.csv",
    dtype=str
)

display(
    raw_exports.loc[
        raw_exports["Country"] == "Brazil",
        ["Country", "2013", "2014", "2015", "2016",
         "2017", "2018", "2019", "Total_export"]
    ]
)

,Country,2013,2014,2015,2016,2017,2018,2019,Total_export
2,Brazil,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056

In [15]:
# Compare Brazil's reported total with the sum of its yearly exports
year_columns = [
    str(year) for year in range(1990, 2020)
]

brazil_years = brazil_exports[year_columns].iloc[0]

print("Reported total:", brazil_exports["Total_export"].iloc[0])
print("Sum of yearly values:", brazil_years.sum())
print("Number of negative yearly values:", (brazil_years < 0).sum())

Reported total: 33807709056
Sum of yearly values: 33807709056
Number of negative yearly values: 3

In [16]:
print("Brazil's values in the original CSV:")

display(
    raw_exports.loc[
        raw_exports["Country"] == "Brazil",
        ["Country", "2013", "2014", "2015", "2016",
         "2017", "2018", "2019", "Total_export"]
    ]
)

Brazil's values in the original CSV:

,Country,2013,2014,2015,2016,2017,2018,2019,Total_export
2,Brazil,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056

In [17]:
# Compare Brazil's total in the original CSV and loaded dataframe

print("Original CSV total:")
print(
    raw_exports.loc[
        raw_exports["Country"] == "Brazil", "Total_export"
    ].to_string(index=False)
)

print("\nLoaded dataframe total:")
print(
    coffee_export.loc[
        coffee_export["Country"] == "Brazil", "Total_export"
    ].to_string(index=False)
)

Original CSV total:
33807709056

Loaded dataframe total:
33807709056

In [18]:
with open("Coffee_export.csv", "r", encoding="utf-8-sig") as file:
    lines = file.readlines()

for line in lines:
    if line.startswith("Brazil,"):
        print(line)
        break

Brazil,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,1388940000,1080960000,1390320000,1678920000,1542660000,1588680000,1571880000,1642140000,1691040000,1770600000,1822680000,1990020000,2028360000,1712940000,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056

### Data Quality Finding: Brazil's Coffee Exports

The original CSV contains the value -2,147,483,648 for Brazil's coffee exports in 2014, 2015, and 2019. These values are suspicious because export totals would not normally be expected to be negative. The values appear in both the original CSV and the loaded Pandas DataFrame, so they were not introduced simply by loading the file.

Brazil's reported total of 33,807,709,056 matches the sum of its yearly values. However, the calculation includes the three suspicious negative values, so this agreement does not prove that the total is accurate. The cause of these values remains unknown, and the original data should be preserved until the issue can be investigated further.

In [19]:

datasets = {
    "Coffee Exports": coffee_export,
    "Coffee Imports": coffee_import,
    "Coffee Production": coffee_production
}

for name, df in datasets.items():
    print(f"\n--- {name} ---")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print(f"Missing cells: {df.isna().sum().sum()}")
    print(f"Duplicate rows: {df.duplicated().sum()}")
    print("Data types:")
    print(df.dtypes)

--- Coffee Exports ---
Rows: 55
Columns: 32
Missing cells: 0
Duplicate rows: 0
Data types:
Country           str
1990            int64
1991            int64
1992            int64
1993            int64
1994            int64
1995            int64
1996            int64
1997            int64
1998            int64
1999            int64
2000            int64
2001            int64
2002            int64
2003            int64
2004            int64
2005            int64
2006            int64
2007            int64
2008            int64
2009            int64
2010            int64
2011            int64
2012            int64
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_export    int64
dtype: object

--- Coffee Imports ---
Rows: 35
Columns: 32
Missing cells: 0
Duplicate rows: 0
Data types:
Country           str
1990            int64
1991            int64
1992            int64
1993            int64
1994            int64
1995            int64
1996            int64
1997            int64
1998            int64
1999            int64
2000            int64
2001            int64
2002            int64
2003            int64
2004            int64
2005            int64
2006            int64
2007            int64
2008            int64
2009            int64
2010            int64
2011            int64
2012            int64
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_import    int64
dtype: object

--- Coffee Production ---
Rows: 55
Columns: 33
Missing cells: 0
Duplicate rows: 0
Data types:
Country                 str
Coffee type             str
1990/91             float64
1991/92             float64
1992/93             float64
1993/94             float64
1994/95             float64
1995/96             float64
1996/97             float64
1997/98             float64
1998/99             float64
1999/00             float64
2000/01             float64
2001/02             float64
2002/03             float64
2003/04             float64
2004/05             float64
2005/06             float64
2006/07             float64
2007/08             float64
2008/09             float64
2009/10             float64
2010/11             float64
2011/12             float64
2012/13             float64
2013/14             float64
2014/15             float64
2015/16             float64
2016/17             float64
2017/18             float64
2018/19             float64
2019/20             float64
Total_production    float64
dtype: object

In [ ]:

# Part 2: Explore and Check the Coffee Datasets

# Create a dictionary that connects each dataset name to its DataFrame.
datasets = {
    "Coffee Exports": coffee_export,
    "Coffee Imports": coffee_import,
    "Coffee Production": coffee_production
}

# Loop through each dataset to examine its size and basic data quality.
for name, df in datasets.items():

    # Print the name of the dataset being examined.
    print(f"\n--- {name} ---")

    # Display the number of rows (records) in the dataset.
    print(f"Rows: {df.shape[0]}")

    # Display the number of columns (variables) in the dataset.
    print(f"Columns: {df.shape[1]}")

    # Count all missing cells in the dataset.
    # The first sum counts missing values in each column;
    # the second sum adds them together for the entire DataFrame.
    print(f"Missing cells: {df.isna().sum().sum()}")

    # Count rows that are exact duplicates of other rows.
    print(f"Duplicate rows: {df.duplicated().sum()}")

    # Count the number of distinct country names in the Country column.
    print(f"Unique countries: {df['Country'].nunique()}")

    # Display all column names, including years and total-value columns.
    print(f"Column names: {df.columns.tolist()}")

--- Coffee Exports ---
Rows: 55
Columns: 32
Missing cells: 0
Duplicate rows: 0
Unique countries: 55
Column names: ['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_export']

--- Coffee Imports ---
Rows: 35
Columns: 32
Missing cells: 0
Duplicate rows: 0
Unique countries: 35
Column names: ['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_import']

--- Coffee Production ---
Rows: 55
Columns: 33
Missing cells: 0
Duplicate rows: 0
Unique countries: 55
Column names: ['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94', '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00', '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', 'Total_production']



**Coffee Exports**

The coffee exports dataset contains 55 rows and 32 columns. My checks found zero missing cells and zero duplicate rows. However, I identified three suspicious negative values of `-2147483648` in Brazil's export data for 2014, 2015, and 2019. These values are unusual for export data and may indicate a data-quality or data-conversion issue. The exact cause has been confirmed and found: The values exist: Brazil's export data contains `-2147483648` for 2014, 2015, and 2019.

1. The original CSV contains them: You loaded `Coffee_export.csv` as text and confirmed that the negative values were already in the file, rather than being introduced simply by loading it into Pandas.
2. The total matches the sum: Brazil's `Total_export` matches the sum of its yearly values, but that sum includes the three suspicious negative numbers. Therefore, the matching total does not prove the data is accurate.

**Coffee Imports**

The coffee imports dataset contains 35 rows and 32 columns. My checks found zero missing cells and zero duplicate rows. The data includes calendar-year columns from 1990 through 2019. No missing-value or duplicate-row problems were identified in my checks. However, these checks do not guarantee that all values are accurate. Unexpected values or inconsistent country names could affect country comparisons or cause problems when combining this dataset with other datasets.

**Coffee Production**

The coffee production dataset contains 55 rows and 33 columns. My checks found zero missing cells and zero duplicate rows. The dataset includes a `Country` column, a `Coffee type` column, coffee-season columns from `1990/91` through `2019/20`, and a `Total_production` column. The seasonal year format differs from the calendar-year format used in the export and import datasets. If I compare these years without accounting for the difference, I could incorrectly align production and trade figures. I should also verify that numerical columns contain appropriate numeric values before performing further calculations.

**Overall Data Quality Assessment**

Based on the checks performed, all three datasets have no detected missing cells or exact duplicate rows. The exports dataset needs the most immediate investigation because of the three suspicious negative values. The different year formats also need attention before comparing production, exports, and imports. If data-quality issues are ignored, they could produce misleading statistics, inaccurate comparisons, and incorrect business conclusions. Before further analysis, I would verify suspicious values against the original source, check country-name consistency, and confirm that the measurement units and reporting periods are comparable.



Based on my exploration, the **coffee imports dataset appears to be the most complete in terms of the basic data-quality checks I performed**. It contains 35 countries, 30 calendar years from 1990 through 2019, and no missing cells or duplicate rows. However, all three datasets passed these same missing-value and duplicate checks, so I cannot conclude that imports is definitively more complete based on these checks alone. The **coffee exports dataset requires the most immediate investigation** because Brazil has three suspicious negative values of `-2147483648` for 2014, 2015, and 2019. These values could distort statistical summaries and trend analysis. The production dataset also requires care because it uses coffee-season years, such as `1990/91` through `2019/20`, instead of calendar years. These different reporting periods must be considered before comparing the datasets.

A global coffee corporation could use these datasets to answer important business questions. For example, which countries produce and export the most coffee? Which countries import the most coffee and might represent promising markets? How have coffee production, exports, and imports changed over time? The company could use these findings to help evaluate potential sourcing countries, identify major import markets, and support supply-chain planning. Before making business decisions, the company should verify the suspicious export values, confirm the measurement units, and account for differences in reporting periods. The datasets provide a useful starting point for market analysis, but additional validation is needed before relying on the results for business decisions.

In [ ]:

# Part 3: Calculate Summary Statistics for Total Values

# Create a list containing each dataset, its name, and its total-value column.
for name, df, total_column in [
    ("Coffee Exports", coffee_export, "Total_export"),
    ("Coffee Imports", coffee_import, "Total_import"),
    ("Coffee Production", coffee_production, "Total_production")
]:
    # Print the dataset name and the column being analyzed.
    print(f"\n{name} — {total_column}")

    # Calculate the minimum, maximum, and average (mean) total values.
    # The agg() method applies all three calculations to the selected column.
    # The round(2) method rounds the results to two decimal places.
    print(df[total_column].agg(["min", "max", "mean"]).round(2))

Coffee Exports — Total_export
min     1.500000e+06
max     3.380771e+10
mean    2.851332e+09
Name: Total_export, dtype: float64

Coffee Imports — Total_import
min     2.970000e+07
max     4.250766e+10
mean    5.069693e+09
Name: Total_import, dtype: float64

Coffee Production — Total_production
min     1.080000e+06
max     7.508298e+10
mean    4.104269e+09
Name: Total_production, dtype: float64